changes in how packages are handled and found, they're now in subdirectories

diff --git a/package/skel/make b/package/skel/make
--- a/package/skel/make
+++ b/package/skel/make
@@ -5,6 +5,14 @@
 PKG_NAME=$(grep 'NAME=' $(dirname "$0")/info | cut -d= -f2)
 # Gets the full path of the package directory
 PKG_DIR="$(cd "$(dirname "${0}")" && pwd)"
+# Shorthand for $PKG_DIR/$PKG_NAME used occasionally
+PKG_PATH="$PKG_DIR/$PKG_NAME"
+
+# Used to output text to the terminal
+log() {
+        format="[ $PKG_NAME ]"
+        printf "$format $1\n"
+}
 
 # The configure script
 # The purpose of this is to clone/get the source, and if the folder/file already exists, check for updates, or replace it
@@ -14,29 +22,31 @@ PKG_DIR="$(cd "$(dirname "${0}")" && pwd)"
 # And every time this function is called, there will be a second variable, defining whether the build is for a local install, or not.
 # If you do not want to make it a local build, set it in 'info'.
 configure() {
-	printf "[$PKG_NAME] Configuring...
-[$PKG_NAME] Cloning into new directory...\n"
+	log "Configuring..."
+	log "Cloning into new directory..."
 
-	git clone $(grep 'SYNC_URL=' $PKG_DIR/info | cut -d= -f2) $PKG_DIR/$PKG_NAME || { printf "[$PKG_NAME] Directory already here, checking for updates...\n"; cd $PKG_DIR/$PKG_NAME; git pull; cd ../; }
+	git clone $(grep 'SYNC_URL=' $PKG_DIR/info | cut -d= -f2) $PKG_PATH || { log "Directory already here, checking for updates..."; cd $PKG_PATH; git pull; cd ../; }
 
 	if [[ $1 == 'y' ]]; then
-		printf "[$PKG_NAME] Local install...\n"
-		sed -i 's|PREFIX ?= .*|PREFIX ?= /home/'$(whoami)'/.local|' $PKG_DIR/$PKG_NAME/Makefile
-		printf "[$PKG_NAME] Changed path to ~/.local/bin/...\n"
+		log "Local install..."
+		sed -i 's|PREFIX ?= .*|PREFIX ?= /home/'$(whoami)'/.local|' $PKG_PATH/Makefile
+		log "Changed path to ~/.local/bin/..."
 	else
-		printf "[$PKG_NAME] Root install...\n"
-		sed -i 's|PREFIX ?= .*|PREFIX ?= /opt|' $PKG_DIR/$PKG_NAME/Makefile
+		log "Root install..."
+		sed -i 's|PREFIX ?= .*|PREFIX ?= /opt|' $PKG_PATH/Makefile
 	fi
 }
+
 
 # Instructions on how to build and install the package.
 # Make the function cd into the source and run make/make install, and then echo the packages name to installed.
 build() {
-	cd $PKG_DIR/$PKG_NAME
-	printf "[$PKG_NAME] Installing...\n"
-	make install || { printf "[$PKG_NAME] Failed to install, aborting...\n"; exit 1; }
-	echo $PKG_NAME >> $PKG_DIR/../installed
+	cd $PKG_PATH
+	log "Installing..."
+	make install || { log "Failed to install, aborting..."; exit 1; }
+	echo $PKG_NAME >> $PKG_DIR/../../installed
 }
+
 
 # Attempts to uninstall the package by leveraging the sources make command
 # If the folder is not found, it exits.
@@ -46,7 +56,7 @@ build() {
 # If you do not have this folder, you can run configure (and make sure its root or local!) and then run this function.
 # Afterwards you can run clean.
 uninstall() {
-	cd $PKG_DIR/$PKG_NAME || { printf "[$PKG_NAME] Package is not installed.\n"; exit 1; }
+	cd $PKG_DIR/$PKG_NAME || { log "Package is not installed."; exit 1; }
 	printf "[$PKG_NAME] Uninstalling...\n"
 	make uninstall
 	sed -i '/'$PKG_NAME'/d' $PKG_DIR/../installed
@@ -54,8 +64,8 @@ uninstall() {
 
 # Deletes the work directory for the package, doesn't remove the package from the system nor the 'installed' file in the root of the repository list
 clean() {
-	printf "[$PKG_NAME] Deleting work dir...\n"
-	rm -rf $PKG_DIR/$PKG_NAME
+	log "Deleting work dir..." $@
+	rm -rf $PKG_PATH
 }
 
 # Makes all of the variables available for all the functions
